import streamlit as st
from PIL import Image
import torch
import torch.nn as nn
from torchvision import models, transforms

st.set_page_config(
    page_title="Crop Disease Detector",
    page_icon="🌿",
    layout="wide")

#Class names
CLASS_NAMES = [
    "Cocoa_Black_Pod_Rot",
    "Cocoa_Healthy",
    "Cocoa_Pod_Borer",
    "Maize_Common_Rust",
    "Maize_Healthy",
    "Maize_Northern_Leaf_Blight",
    "Tomato_Early_Blight",
    "Tomato_Healthy",
    "Tomato_Late_Blight",
    "Tomato_Leaf_Mold"
]

#Loading model
@st.cache_resource
def load_model():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = models.mobilenet_v3_large(weights=None)

    model.classifier[3] = nn.Linear(
        model.classifier[3].in_features,
        len(CLASS_NAMES))

    model.load_state_dict(
        torch.load(
            "models/crop_disease_model.pth",
            map_location=device))

    model = model.to(device)
    model.eval()
    return model, device

#Image Preprocessing
inference_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225])
    ])

#Prediction Function
def predict_disease(image, model, device):
    image = image.convert("RGB")

    image_tensor = inference_transform(image)
    image_tensor = image_tensor.unsqueeze(0)
    image_tensor = image_tensor.to(device)

    with torch.inference_mode():
        outputs = model(image_tensor)
        probabilities = torch.softmax(outputs,dim=1)

        confidence, predicted_class = torch.max(probabilities,dim=1)

    predicted_index = predicted_class.item()
    disease = CLASS_NAMES[predicted_index]
    confidence = confidence.item()
    return disease, confidence




col1, col2 = st.columns([5, 1])

with col1:
    st.title("🌿 Crop Disease Detector")
    st.caption("Helping farmers identify crop diseases using Artificial Intelligence.")

with col2:
    language = st.selectbox(
        "🌍 Language",
        ["English", "Twi", "Ga", "Ewe"])
st.divider()

left_column,right_column = st.columns([2,3])

with left_column:
    st.subheader("📷 Upload or Capture Image")
    image_source = st.radio("Choose Image Source",
        ["Upload Image", "Take Photo"])

    image= None
    if image_source=="Upload Image":
        uploaded_file = st.file_uploader(
            "Upload a crop leaf image",
            type=["jpg","jpeg","png"]
        )
        if uploaded_file:
            image = Image.open(uploaded_file)

    else:
        camera_photo = st.camera_input("Take a picture of the leaf")
        if camera_photo:
            image = Image.open(camera_photo)

    if image:
        st.image(
            image,caption="Leaf Preview",
            use_container_width=True
        )
        st.info("💡 Tip: Use a clear photo with good lighting for the best prediction.")

        if st.button("🔍 Detect Disease",type="primary",use_container_width=True):
            with st.spinner("Analyzing the leaf..."):
                model,device = load_model()
                disease,confidence = predict_disease(image,model,device)

            with right_column:
                st.subheader("Prediction Result")
                display_name = disease.replace( "_"," ")

                st.success(f"**Prediction:** {display_name}")
                st.metric("Confidence",f"{confidence * 100:.2f}%")
                st.caption("Prediction generated by the GreenPulse MobileNetV3 model.")
            


