import streamlit as st
from PIL import Image
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms

st.set_page_config(
    page_title="Crop Disease Detector",
    page_icon="🌿",
    layout="wide")

#Class names
CLASS_NAMES = [
    "Maize_Northern_Leaf_Blight",
    "Tomato_Late_Blight",
    "Tomato_Healthy",
    "Maize_Healthy",
    "Cocoa_Healthy",
    "Cocoa_Pod_Borer",
    "Cocoa_Black_Pod_Rot",
    "Tomato_Leaf_Mold",
    "Maize_Common_Rust",
    "Tomato_Early_Blight"
]

#Loading model
class GreenPulseCustomCNN(nn.Module):
    def __init__(self, num_classes=10):
        super(GreenPulseCustomCNN, self).__init__()

        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)

        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)

        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.bn3 = nn.BatchNorm2d(128)

        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.dropout = nn.Dropout(0.3)

        self.fc1 = nn.Linear(128 * 28 * 28, 256)
        self.fc2 = nn.Linear(256, num_classes)

    def forward(self, x):
        x = self.pool(F.relu(self.bn1(self.conv1(x))))
        x = self.pool(F.relu(self.bn2(self.conv2(x))))
        x = self.pool(F.relu(self.bn3(self.conv3(x))))

        x = torch.flatten(x, 1)

        x = self.dropout(F.relu(self.fc1(x)))
        x = self.fc2(x)

        return x


@st.cache_resource
def load_model():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model = GreenPulseCustomCNN(
        num_classes=len(CLASS_NAMES)
    ).to(device)

    model.load_state_dict(
        torch.load(
            "models/custom_greenpulse_model.pth",
            map_location=device
        )
    )
    model.eval()
    return model, device

#Image Preprocessing
inference_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225])
    ])

#Prediction Function
def predict_disease(image, model, device):
    image = image.convert("RGB")

    image_tensor = inference_transform(image)
    image_tensor = image_tensor.unsqueeze(0)
    image_tensor = image_tensor.to(device)

    with torch.inference_mode():
        outputs = model(image_tensor)
        probabilities = torch.softmax(outputs,dim=1)

        confidence, predicted_class = torch.max(probabilities,dim=1)

    predicted_index = predicted_class.item()
    disease = CLASS_NAMES[predicted_index]
    confidence = confidence.item()
    return disease, confidence


col1, col2 = st.columns([5, 1])

with col1:
    st.title("🌿 Crop Disease Detector")
    st.caption("Helping farmers identify crop diseases using Artificial Intelligence.")

with col2:
    language = st.selectbox(
        "🌍 Language",
        ["English", "Twi", "Ga", "Ewe"])
st.divider()

left_column,right_column = st.columns([2,3])

with left_column:
    st.subheader("📷 Upload or Capture Image")
    image_source = st.radio("Choose Image Source",
        ["Upload Image", "Take Photo"])

    image= None
    if image_source=="Upload Image":
        uploaded_file = st.file_uploader(
            "Upload a crop leaf image",
            type=["jpg","jpeg","png"]
        )
        if uploaded_file:
            image = Image.open(uploaded_file)

    else:
        camera_photo = st.camera_input("Take a picture of the leaf")
        if camera_photo:
            image = Image.open(camera_photo)

    if image:
        st.image(
            image,caption="Leaf Preview",
            use_container_width=True
        )
        st.info("💡 Tip: Use a clear photo with good lighting for the best prediction.")

        if st.button("🔍 Detect Disease",type="primary",use_container_width=True):
            with st.spinner("Analyzing the leaf..."):
                model,device = load_model()
                disease,confidence = predict_disease(image,model,device)

            with right_column:
                st.subheader("Prediction Result")
                display_name = disease.replace( "_"," ")

                st.success(f"**Prediction:** {display_name}")
                st.metric("Confidence",f"{confidence * 100:.2f}%")
                st.caption("Prediction generated by the GreenPulse MobileNetV3 model.")
            


